### ISSUE TITLE
The `make_GLM_grids.py` example fails

### ISSUE THREAD

**Issue by simonrp84** [deeplycloudy/glmtools#82]
Hello, I'm trying to grid some GLM data and am looking at the `make_GLM_grids.py` example script.
I try to run it with this:
`python make_GLM_grids.py -o ./OUT/ --ngroups 3 --ctr_lat 13.333 --ctr_lon -61.183 --width 800 --height 800 ./OR_GLM-L2-LCFA_G16_s2021102*.nc`

But I get this error:
```
Traceback (most recent call last):
  File "make_GLM_grids.py", line 329, in <module>
    gridder(glm_filenames, start_time, end_time, **grid_kwargs)
  File "/home/proud/PycharmProjects/glmtools/glmtools/grid/make_grids.py", line 838, in grid_GLM_flashes
    outputs = list(map(this_proc_each_grid, subgrids))
  File "/home/proud/PycharmProjects/glmtools/glmtools/grid/make_grids.py", line 877, in proc_each_grid
    gridder = GLMGridder(start_time, end_time, **kwargsij)
  File "/home/proud/PycharmProjects/lmatools/lmatools/grid/make_grids.py", line 202, in __init__
    self.pipeline_setup()
  File "/home/proud/PycharmProjects/glmtools/glmtools/grid/make_grids.py", line 237, in pipeline_setup
    (init_density_grid, extent_density_grid, footprint_grid,
ValueError: not enough values to unpack (expected 4, got 3)
```

Any thoughts on what could be wrong here, and how to resolve it? Thanks!

**Comment by deeplycloudy** [comment]
Hi @simonrp84 that's could be a version mismatch with lmatools, but master should be consistent for glmtools and lmatools for at least the past year. The other possibility is that you're hitting an old calling path that hasn't been exercised very much. Does it go away if you add `--fixed_grid --split_events --goes_position east`? Does removing `--ngroups` make a difference?

**Comment by simonrp84** [comment]
Thanks for the reply. Am off work for the next few days (school holidays!) but will try your suggestions as soon as possible.
